SET NAMES utf8mb4;
USE TOURDULICH;

DELETE FROM articles WHERE id = 3;

UPDATE articles SET
  a_title = 'Top 10 Điểm Du Lịch Việt Nam Không Thể Bỏ Qua Năm 2026',
  a_slug  = 'top-10-diem-du-lich-viet-nam-2026',
  a_show_home = 1, a_active = 1,
  a_description = '<p>Việt Nam sở hữu những điểm đến tuyệt vời từ Bắc đến Nam — từ vịnh Hạ Long huyền ảo, phố cổ Hội An lung linh đến biển đảo Phú Quốc hoang sơ. Cùng VHD Travel khám phá 10 điểm đến hot nhất 2026!</p>',
  a_content = '<h3>1. Vịnh Hạ Long — Di sản Thiên nhiên Thế giới</h3><p>Vịnh Hạ Long với hơn 1.600 hòn đảo đá vôi sừng sững giữa làn nước ngọc lục bảo là điểm đến không thể thiếu. Trải nghiệm ngủ đêm trên du thuyền, khám phá hang động Thiên Cung, Đầu Gỗ...</p><h3>2. Phố Cổ Hội An — Ánh Đèn Lồng Lung Linh</h3><p>Hội An được UNESCO công nhận là Di sản Văn hóa Thế giới với không gian cổ kính, đèn lồng đủ màu sắc lung linh về đêm...</p><h3>3. Phú Quốc — Đảo Ngọc Xanh Biếc</h3><p>Phú Quốc với bãi biển hoang sơ, nước biển trong vắt là thiên đường nghỉ dưỡng hàng đầu Đông Nam Á. Vinpearl Safari, Grand World, cáp treo Hòn Thơm...</p><h3>4. Sapa — Mây Trời Tây Bắc</h3><p>Sapa thu hút du khách bởi ruộng bậc thang vàng óng mùa lúa chín, đỉnh Fansipan hùng vĩ, bản làng dân tộc thiểu số đầy màu sắc...</p><h3>5. Đà Lạt — Thành Phố Ngàn Hoa</h3><p>Đà Lạt với khí hậu mát lạnh quanh năm, vườn hoa rực rỡ và những đồi thông xanh mướt là điểm đến lý tưởng cho cặp đôi và gia đình...</p>',
  updated_at = '2025-12-01 09:00:00', created_at = '2025-11-15 08:00:00'
WHERE id = 1;

UPDATE articles SET
  a_title = 'Kinh Nghiệm Du Lịch Đà Nẵng 2026 — Ăn Gì, Ở Đâu, Chơi Gì?',
  a_slug  = 'kinh-nghiem-du-lich-da-nang-2026',
  a_show_home = 1, a_active = 1,
  a_description = '<p>Đà Nẵng — thành phố đáng sống nhất Việt Nam với bãi biển Mỹ Khê tuyệt đẹp, cầu Rồng phun lửa, Bà Nà Hills huyền ảo. Bộ cẩm nang đầy đủ nhất cho chuyến đi Đà Nẵng 2026!</p>',
  a_content = '<h3>Thời điểm lý tưởng để đến Đà Nẵng</h3><p>Tháng 1-8 là thời điểm đẹp nhất, thời tiết nắng ấm, biển lặng. Festival Pháo hoa Đà Nẵng tổ chức vào tháng 6-7 thu hút hàng triệu khách.</p><h3>Di chuyển</h3><p>Bay thẳng từ Hà Nội/TP.HCM: 1h20 phút. Từ sân bay về trung tâm: taxi Grab khoảng 100.000đ (15-20 phút).</p><h3>Ở đâu?</h3><p>Bãi biển Mỹ Khê lý tưởng nhất với nhiều khách sạn từ bình dân đến 5 sao. Khu Sơn Trà có InterContinental, Marriott — view tuyệt vời.</p><h3>Ăn gì?</h3><p>Mì Quảng, Bánh mì Bà Lan, Bún chả cá, Bánh xèo, Hải sản tươi tại bờ biển Mỹ Khê...</p><h3>Chơi gì?</h3><p>Bà Nà Hills và Cầu Vàng, Ngũ Hành Sơn, Bán đảo Sơn Trà, Phố cổ Hội An (30km), Cầu Rồng phun lửa tối thứ 7 và Chủ nhật...</p>',
  updated_at = '2025-12-10 10:00:00', created_at = '2025-12-01 09:00:00'
WHERE id = 2;

INSERT INTO articles (a_title, a_slug, a_show_home, a_active, a_view, a_description, a_avatar, a_content, a_category_id, a_user_id, created_at, updated_at) VALUES
('Bí Quyết Săn Vé Máy Bay Rẻ Cho Mùa Hè 2026', 'bi-quyet-san-ve-may-bay-re-2026', 1, 1, 0, '<p>Bạn muốn du lịch mùa hè 2026 với chi phí tiết kiệm tối đa? Đây là những bí quyết vàng giúp bạn săn vé máy bay giá rẻ hiệu quả nhất từ các chuyên gia VHD Travel.</p>', '2023-06-09__db13126498f89573b02eb658db0cbed4.jpg', '<h3>1. Đặt vé sớm — Nguyên tắc vàng</h3><p>Đặt vé trước 3-6 tháng thường có giá rẻ hơn 30-50% so với đặt gần ngày khởi hành. Các hãng hàng không thường mở bán vé sớm với giá ưu đãi nhất.</p><h3>2. Linh hoạt về ngày bay</h3><p>Bay vào thứ 3, thứ 4 thường rẻ hơn cuối tuần. Các chuyến bay sáng sớm và tối muộn cũng thường có giá tốt hơn.</p><h3>3. Theo dõi Flash Sale</h3><p>Vietnam Airlines, Vietjet, Bamboo Airways thường xuyên có Flash Sale với giá vé 0đ hoặc cực rẻ. Đăng ký nhận email thông báo từ các hãng để không bỏ lỡ.</p><h3>4. So sánh giá trên nhiều kênh</h3><p>Sử dụng Google Flights, Skyscanner, Traveloka để so sánh giá từ nhiều hãng và đại lý cùng lúc.</p><h3>5. Combo vé máy bay + khách sạn</h3><p>Đặt combo thường tiết kiệm 15-25% so với đặt riêng lẻ. VHD Travel cung cấp nhiều gói combo hấp dẫn cho mùa hè 2026.</p>', 1, 1, '2025-12-15 08:00:00', '2025-12-15 08:00:00'),
('Resort 5 Sao Phú Quốc — Trải Nghiệm Đẳng Cấp 2026', 'resort-5-sao-phu-quoc-2026', 1, 1, 0, '<p>Phú Quốc ngày càng khẳng định vị thế là điểm đến nghỉ dưỡng hàng đầu Đông Nam Á với hàng loạt resort 5 sao đẳng cấp quốc tế. Đây là những resort tốt nhất không nên bỏ lỡ năm 2026.</p>', '2023-06-09__19c10f4e66067da4b5eb1dac874e4672.jpg', '<h3>1. JW Marriott Phu Quoc Emerald Bay</h3><p>Kiến trúc lấy cảm hứng từ Đại học Lamarck hư cấu, JW Marriott Phú Quốc mang đến trải nghiệm độc nhất vô nhị. Bãi biển riêng Khem đẹp nhất Phú Quốc.</p><h3>2. Premier Village Phu Quoc Resort</h3><p>Villa trên mỏm đá tại Mũi Ông Đội, tầm nhìn 270° ra biển. Ngắm cả bình minh lẫn hoàng hôn từ cùng một vị trí. Đạt giải Best Resort in Vietnam 2025.</p><h3>3. Vinpearl Discovery 3</h3><p>Nằm trong quần thể Vinpearl Phú Quốc, lý tưởng cho gia đình có trẻ em với vô số hoạt động giải trí và Vinpearl Safari.</p><h3>Lời khuyên đặt phòng</h3><p>Đặt trước ít nhất 2-3 tháng cho mùa cao điểm tháng 11 đến tháng 4. Đặt trực tiếp qua website resort để giá tốt nhất và nhiều ưu đãi tặng kèm.</p>', 1, 1, '2026-01-05 09:00:00', '2026-01-05 09:00:00'),
('Hướng Dẫn Du Lịch Sapa Mùa Lúa Vàng 2026', 'du-lich-sapa-mua-lua-vang-2026', 1, 1, 0, '<p>Tháng 9-10 là thời điểm ruộng bậc thang Sapa khoác tấm áo vàng óng tuyệt đẹp. Đây là cẩm nang chi tiết nhất để có chuyến Sapa hoàn hảo trong mùa lúa vàng 2026.</p>', '2023-06-09__e27ab46ee4c0d827e3d5e9c97fdf20f4.jpg', '<h3>Thời điểm vàng để lên Sapa</h3><p>Mùa lúa chín: Tháng 9-10 (ruộng bậc thang vàng óng đẹp nhất). Mùa hoa: Tháng 3-4 (hoa mận, hoa đào trắng tinh). Tháng 5-8 khí hậu mát mẻ, xanh tươi.</p><h3>Di chuyển lên Sapa</h3><p>Tàu hỏa Hà Nội - Lào Cai: 8-9 tiếng từ 200.000đ. Xe khách giường nằm: 5-6 tiếng từ 150.000đ. Từ Lào Cai lên Sapa: 40km taxi hoặc xe buýt.</p><h3>Các điểm check-in nổi tiếng</h3><p>Ruộng bậc thang Mù Cang Chải đẹp nhất mùa vàng, Bản Cát Cát làng văn hóa H\'Mông, Đỉnh Fansipan 3.143m, Thác Bạc và Cầu Mây, Chợ phiên cuối tuần tại thị trấn Sapa.</p><h3>Ở đâu tại Sapa?</h3><p>Topas Ecolodge có view đẹp nhất, Sapa Jade Hill Resort, Victoria Sapa Resort, hoặc homestay tại bản làng từ 100.000đ/đêm để trải nghiệm văn hóa thực sự.</p>', 1, 1, '2026-01-20 10:00:00', '2026-01-20 10:00:00'),
('Xu Hướng Du Lịch Xanh & Bền Vững Tại Việt Nam 2026', 'xu-huong-du-lich-xanh-2026', 1, 1, 0, '<p>Du lịch xanh (eco-tourism) và bền vững đang bùng nổ mạnh mẽ tại Việt Nam năm 2026. Cùng tìm hiểu cách du lịch có trách nhiệm và những điểm đến eco-friendly hàng đầu!</p>', '2023-06-09__b9948d600fd80d5fb83bc6cc6149e307.jpg', '<h3>Du lịch xanh là gì?</h3><p>Du lịch xanh tập trung vào bảo tồn thiên nhiên, hỗ trợ cộng đồng địa phương và giảm thiểu tác động tiêu cực đến môi trường. Đây không chỉ là xu hướng mà còn là trách nhiệm của mỗi du khách.</p><h3>Top điểm đến eco-tourism tại Việt Nam</h3><p>Côn Đảo với Six Senses dẫn đầu về du lịch sinh thái và bảo tồn rùa biển. Ninh Thuận với Amanoi Resort giữa vườn quốc gia Núi Chúa. Phong Nha - Kẻ Bàng với hệ thống hang động lớn nhất thế giới. Mù Cang Chải với văn hóa H\'Mông và ruộng bậc thang.</p><h3>Nguyên tắc du lịch có trách nhiệm</h3><p>Không xả rác, mang rác về. Không mua sản phẩm từ động vật hoang dã. Ưu tiên dịch vụ địa phương về ăn, ở, hướng dẫn. Tôn trọng văn hóa bản địa. Chọn resort và tour có chứng chỉ xanh.</p><h3>VHD Travel cam kết</h3><p>100% tour VHD Travel đối tác với các đơn vị cam kết giảm thiểu rác nhựa, hỗ trợ cộng đồng địa phương và bảo vệ hệ sinh thái Việt Nam.</p>', 1, 1, '2026-02-01 08:00:00', '2026-02-01 08:00:00');

SELECT id, a_title, DATE(created_at) as date FROM articles ORDER BY id;
